const mongoose= require('mongoose');

const ProfileSchema=mongoose.Schema({
    user:{
        type:mongoose.Schema.Types.ObjectId,
        ref:'user'
    },
    handle:{
        type:String,
        required:true
    },
    company:{
        type:String,
        required:true
    },
    location:{
        type:String,
        required:true
    },  
    status:{
        type:String,
        required:true
    },
    skills:{
        type:[String],
        required:true
    },
    website:{
        type:String,
        required:true
    },
    experience:[
        {
            title:{
                type:String,
            },
            company:{
                type:String
            },
            location:{
                type:String
            },
            from:{
                type:Date
            },
            To:{
                type:Date
            },
            current:{
                type:String
            }
        }
    ],
    education:[{
        school:{
            type:String
        },
        degree:{
            type:String
        },
        fieldofstudy:{
            type:String
        },
        from:{
            type:Date
        },
        To:{
            type:Date
        },
        current:{
            type:String
        }
    }],
    social:[{
        facebook:{
            type:String
        },
        twitter:{
            type:String
        },
        youtube:{
            type:String
        },
        linkedin:{
            type:String
        },
        instagram:{
            type:String
        }
    }],
    date:{
        type:String,
        default:Date.now
    }
})

module.exports=mongoose.model('profile',ProfileSchema);